apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo   
  template:
    metadata:
      labels:
        app: mongo 
    spec:
      containers:
      - name: mongo-deployment
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
           secretKeyRef:
            name: mysecret
            key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mysecret
            key: password
        volumeMounts: 
         - name: mongo-data
           mountPath: /data/db  
      volumes: 
      - name: mongo-data
        persistentVolumeClaim: 
         claimName: mongo-pvc      
